package com.logiplatform.model;

import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="cargo_documents")
public class CargoDocument {
 @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="shipment_id",nullable=false) private UUID shipmentId; @Column(name="document_type",nullable=false) private String documentType; @Column(name="template_code",nullable=false) private String templateCode; @Column(name="file_uri") private String fileUri; @Column(name="content_hash") private String contentHash; @Column(name="status",nullable=false) private String status="DRAFT"; @Column(name="version_no",nullable=false) private Integer versionNo=1; @Column(name="supersedes_document_id") private UUID supersedesDocumentId; @Column(name="customer_visible",nullable=false) private boolean customerVisible=false; @Column(name="uploaded_by") private UUID uploadedBy; @Column(name="file_size_bytes") private Long fileSizeBytes; @Column(name="mime_type") private String mimeType; @Column(name="checksum_sha256") private String checksumSha256; @Column(name="updated_at",nullable=false) private Instant updatedAt=Instant.now(); @Column(name="created_at",nullable=false) private Instant createdAt=Instant.now();
 protected CargoDocument(){} public CargoDocument(UUID t,UUID s,String type,String template,String uri,String hash){tenantId=t;shipmentId=s;documentType=type;templateCode=template;fileUri=uri;contentHash=hash;}
 public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getShipmentId(){return shipmentId;} public String getDocumentType(){return documentType;} public String getTemplateCode(){return templateCode;} public String getFileUri(){return fileUri;} public String getContentHash(){return contentHash;} public String getStatus(){return status;} public Integer getVersionNo(){return versionNo;} public UUID getSupersedesDocumentId(){return supersedesDocumentId;} public boolean isCustomerVisible(){return customerVisible;} public UUID getUploadedBy(){return uploadedBy;} public Long getFileSizeBytes(){return fileSizeBytes;} public String getMimeType(){return mimeType;} public String getChecksumSha256(){return checksumSha256;} public Instant getUpdatedAt(){return updatedAt;} public Instant getCreatedAt(){return createdAt;} public void setLifecycle(int version,UUID supersedes,UUID uploadedBy,boolean customerVisible,Long size,String mime,String checksum){this.versionNo=version;this.supersedesDocumentId=supersedes;this.uploadedBy=uploadedBy;this.customerVisible=customerVisible;this.fileSizeBytes=size;this.mimeType=mime;this.checksumSha256=checksum;this.updatedAt=Instant.now();}
}
