package com.logiplatform.model;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="carrier_tenders",uniqueConstraints=@UniqueConstraint(name="uk_tender_key",columnNames={"tenant_id","tender_key"}))
public class CarrierTender {
 @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="shipment_id") private UUID shipmentId; @Column(name="trip_id") private UUID tripId; @Column(name="tender_key",nullable=false) private String tenderKey; @Column(name="carrier_name",nullable=false) private String carrierName; @Column(name="carrier_contact") private String carrierContact; @Column(name="quoted_amount",precision=19,scale=4) private BigDecimal quotedAmount; @Column(name="currency",nullable=false) private String currency="USD"; @Column(name="status",nullable=false) private String status="SENT"; @Column(name="expires_at") private Instant expiresAt; @Column(name="response_note",columnDefinition="text") private String responseNote; @Column(name="created_at",nullable=false) private Instant createdAt=Instant.now(); @Column(name="responded_at") private Instant respondedAt;
 protected CarrierTender(){} public CarrierTender(UUID t,UUID s,UUID trip,String key,String carrier,String contact,BigDecimal amount,String currency,Instant expires,String note){tenantId=t;shipmentId=s;tripId=trip;tenderKey=key;carrierName=carrier;carrierContact=contact;quotedAmount=amount;this.currency=currency==null?"USD":currency;expiresAt=expires;responseNote=note;}
 public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getShipmentId(){return shipmentId;} public UUID getTripId(){return tripId;} public String getTenderKey(){return tenderKey;} public String getCarrierName(){return carrierName;} public String getCarrierContact(){return carrierContact;} public BigDecimal getQuotedAmount(){return quotedAmount;} public String getCurrency(){return currency;} public String getStatus(){return status;} public Instant getExpiresAt(){return expiresAt;} public String getResponseNote(){return responseNote;} public Instant getCreatedAt(){return createdAt;} public Instant getRespondedAt(){return respondedAt;}
 public void accept(String note){status="ACCEPTED";responseNote=note;respondedAt=Instant.now();} public void reject(String note){status="REJECTED";responseNote=note;respondedAt=Instant.now();} public void expire(){status="EXPIRED";respondedAt=Instant.now();}
}
