package com.logiplatform.model;

import jakarta.persistence.*; import java.time.LocalDate; import java.util.UUID;
@Entity @Table(name="client_records",uniqueConstraints=@UniqueConstraint(name="uk_client_id",columnNames={"tenant_id","client_id"}))
public class ClientRecord {
 @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="client_id",nullable=false) private String clientId; @Column(name="client_company") private String clientCompany; @Column(name="contact_person") private String contactPerson; @Column(name="phone") private String phone; @Column(name="email") private String email; @Column(name="industry") private String industry; @Column(name="country") private String country; @Column(name="city") private String city; @Column(name="lead_source") private String leadSource; @Column(name="client_status") private String clientStatus; @Column(name="relationship_owner") private String relationshipOwner; @Column(name="next_follow_up") private LocalDate nextFollowUp; @Column(name="notes",columnDefinition="text") private String notes;
 protected ClientRecord(){} public ClientRecord(UUID t,String id,String company,String contact,String phone,String email,String industry,String country,String city,String lead,String status,String owner,LocalDate next,String notes){tenantId=t;clientId=id;clientCompany=company;contactPerson=contact;this.phone=phone;this.email=email;this.industry=industry;this.country=country;this.city=city;leadSource=lead;clientStatus=status;relationshipOwner=owner;nextFollowUp=next;this.notes=notes;}
 public void changeStatus(String value){clientStatus=value;} public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public String getClientId(){return clientId;} public String getClientCompany(){return clientCompany;} public String getContactPerson(){return contactPerson;} public String getPhone(){return phone;} public String getEmail(){return email;} public String getIndustry(){return industry;} public String getCountry(){return country;} public String getCity(){return city;} public String getLeadSource(){return leadSource;} public String getClientStatus(){return clientStatus;} public String getRelationshipOwner(){return relationshipOwner;} public LocalDate getNextFollowUp(){return nextFollowUp;} public String getNotes(){return notes;}
}
