package com.logiplatform.model;

import jakarta.persistence.*; import java.time.*; import java.util.UUID;
@Entity @Table(name="customs_declarations",uniqueConstraints=@UniqueConstraint(name="uk_customs_ref",columnNames={"tenant_id","shipment_id","declaration_type"}))
public class CustomsDeclaration {
 @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="shipment_id",nullable=false) private UUID shipmentId; @Column(name="declaration_type",nullable=false) private String declarationType; @Column(name="customs_authority") private String customsAuthority; @Column(name="broker_name") private String brokerName; @Column(name="hs_codes",columnDefinition="text") private String hsCodes; @Column(name="country_of_origin") private String countryOfOrigin; @Column(name="declared_value",precision=19,scale=4) private java.math.BigDecimal declaredValue; @Column(name="currency") private String currency; @Column(name="status",nullable=false) private String status="DRAFT"; @Column(name="external_reference") private String externalReference; @Column(name="submission_message",columnDefinition="text") private String submissionMessage; @Column(name="submitted_at") private Instant submittedAt;
 protected CustomsDeclaration(){} public CustomsDeclaration(UUID t,UUID s,String type,String authority,String broker,String hs,String country,java.math.BigDecimal value,String currency){tenantId=t;shipmentId=s;declarationType=type;customsAuthority=authority;brokerName=broker;hsCodes=hs;countryOfOrigin=country;declaredValue=value;this.currency=currency;}
 public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getShipmentId(){return shipmentId;} public String getDeclarationType(){return declarationType;} public String getCustomsAuthority(){return customsAuthority;} public String getBrokerName(){return brokerName;} public String getHsCodes(){return hsCodes;} public String getCountryOfOrigin(){return countryOfOrigin;} public java.math.BigDecimal getDeclaredValue(){return declaredValue;} public String getCurrency(){return currency;} public String getStatus(){return status;} public String getExternalReference(){return externalReference;} public String getSubmissionMessage(){return submissionMessage;} public Instant getSubmittedAt(){return submittedAt;}
 public void readyForSubmission(){if(hsCodes==null||hsCodes.isBlank())throw new IllegalStateException("HS codes are required");status="READY_FOR_SUBMISSION";}
 public void submit(String ref,String msg){status="SUBMITTED";externalReference=ref;submissionMessage=msg;submittedAt=Instant.now();}
}
