package com.logiplatform.model;

import jakarta.persistence.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.UUID;
@Entity @Table(name="expense_records",uniqueConstraints=@UniqueConstraint(name="uk_expense_id",columnNames={"tenant_id","expense_id"}))
public class ExpenseRecord {
 @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="expense_id",nullable=false) private String expenseId; @Column(name="expense_date",nullable=false) private LocalDate expenseDate; @Column(name="type") private String type; @Column(name="category") private String category; @Column(name="shipment_id") private UUID shipmentId; @Column(name="client") private String client; @Column(name="vendor_payee") private String vendorPayee; @Column(name="description",columnDefinition="text") private String description; @Column(name="currency",nullable=false) private String currency; @Column(name="original_amount",nullable=false,precision=19,scale=4) private BigDecimal originalAmount; @Column(name="exchange_rate_to_usd",precision=19,scale=8) private BigDecimal exchangeRateToUsd; @Column(name="usd_equivalent",precision=19,scale=4) private BigDecimal usdEquivalent; @Column(name="payment_method") private String paymentMethod; @Column(name="status") private String status; @Column(name="approved_by") private String approvedBy;
 protected ExpenseRecord(){} public ExpenseRecord(UUID t,String id,LocalDate date,String type,String category,UUID shipment,String client,String vendor,String desc,String currency,BigDecimal amount,BigDecimal fx,String method,String status,String approved){tenantId=t;expenseId=id;expenseDate=date;this.type=type;this.category=category;shipmentId=shipment;this.client=client;vendorPayee=vendor;description=desc;this.currency=currency;originalAmount=amount;exchangeRateToUsd=fx;usdEquivalent=fx==null?null:amount.multiply(fx);paymentMethod=method;this.status=status;approvedBy=approved;}
 public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public String getExpenseId(){return expenseId;} public LocalDate getExpenseDate(){return expenseDate;} public String getType(){return type;} public String getCategory(){return category;} public UUID getShipmentId(){return shipmentId;} public String getClient(){return client;} public String getVendorPayee(){return vendorPayee;} public String getDescription(){return description;} public String getCurrency(){return currency;} public BigDecimal getOriginalAmount(){return originalAmount;} public BigDecimal getExchangeRateToUsd(){return exchangeRateToUsd;} public BigDecimal getUsdEquivalent(){return usdEquivalent;} public String getPaymentMethod(){return paymentMethod;} public String getStatus(){return status;} public String getApprovedBy(){return approvedBy;}
}
