package com.logiplatform.model;

import jakarta.persistence.*; import java.time.LocalDate; import java.util.UUID;
@Entity @Table(name="partner_records",uniqueConstraints=@UniqueConstraint(name="uk_partner_id",columnNames={"tenant_id","partner_id"}))
public class PartnerRecord {
 @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="partner_id",nullable=false) private String partnerId; @Column(name="country") private String country; @Column(name="company") private String company; @Column(name="contact_person") private String contactPerson; @Column(name="phone") private String phone; @Column(name="email") private String email; @Column(name="services",columnDefinition="text") private String services; @Column(name="city_port_airport") private String cityPortAirport; @Column(name="payment_terms") private String paymentTerms; @Column(name="rating") private Integer rating; @Column(name="status") private String status; @Column(name="last_verified") private LocalDate lastVerified; @Column(name="notes",columnDefinition="text") private String notes;
 protected PartnerRecord(){} public PartnerRecord(UUID t,String id,String country,String company,String contact,String phone,String email,String services,String loc,String terms,Integer rating,String status,LocalDate verified,String notes){tenantId=t;partnerId=id;this.country=country;this.company=company;contactPerson=contact;this.phone=phone;this.email=email;this.services=services;cityPortAirport=loc;paymentTerms=terms;this.rating=rating;this.status=status;lastVerified=verified;this.notes=notes;}
 public void changeStatus(String value){status=value;} public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public String getPartnerId(){return partnerId;} public String getCountry(){return country;} public String getCompany(){return company;} public String getContactPerson(){return contactPerson;} public String getPhone(){return phone;} public String getEmail(){return email;} public String getServices(){return services;} public String getCityPortAirport(){return cityPortAirport;} public String getPaymentTerms(){return paymentTerms;} public Integer getRating(){return rating;} public String getStatus(){return status;} public LocalDate getLastVerified(){return lastVerified;} public String getNotes(){return notes;}
}
