package com.logiplatform.model;

import jakarta.persistence.*; import java.time.*; import java.util.UUID;
@Entity @Table(name="task_records",uniqueConstraints=@UniqueConstraint(name="uk_task_id",columnNames={"tenant_id","task_id"}))
public class TaskRecord {
 @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="task_id",nullable=false) private String taskId; @Column(name="created_date",nullable=false) private LocalDate createdDate; @Column(name="department") private String department; @Column(name="related_reference") private String relatedReference; @Column(name="task",nullable=false) private String task; @Column(name="priority") private String priority; @Column(name="owner") private String owner; @Column(name="due_date") private LocalDate dueDate; @Column(name="status") private String status; @Column(name="completion_date") private LocalDate completionDate; @Column(name="notes",columnDefinition="text") private String notes;
 protected TaskRecord(){} public TaskRecord(UUID t,String id,LocalDate date,String dept,String rel,String task,String pri,String owner,LocalDate due,String status,LocalDate done,String notes){tenantId=t;taskId=id;createdDate=date;department=dept;relatedReference=rel;this.task=task;priority=pri;this.owner=owner;dueDate=due;this.status=status;completionDate=done;this.notes=notes;}
 public void changeStatus(String value){status=value; if("Completed".equalsIgnoreCase(value)) completionDate=LocalDate.now();} public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public String getTaskId(){return taskId;} public LocalDate getCreatedDate(){return createdDate;} public String getDepartment(){return department;} public String getRelatedReference(){return relatedReference;} public String getTask(){return task;} public String getPriority(){return priority;} public String getOwner(){return owner;} public LocalDate getDueDate(){return dueDate;} public String getStatus(){return status;} public LocalDate getCompletionDate(){return completionDate;} public String getNotes(){return notes;} public long getDaysRemaining(){return dueDate==null?0:java.time.temporal.ChronoUnit.DAYS.between(LocalDate.now(),dueDate);} public boolean isOverdue(){return dueDate!=null&&getDaysRemaining()<0&&!"Completed".equalsIgnoreCase(status)&&!"Cancelled".equalsIgnoreCase(status);}
}
