package com.logiplatform.model;

import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="warehouse_tasks")
public class WarehouseTask {
 @Id @GeneratedValue private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="warehouse_id",nullable=false) private UUID warehouseId; @Column(name="shipment_id") private UUID shipmentId; @Column(name="inventory_item_id") private UUID inventoryItemId; @Column(name="task_type",nullable=false) private String taskType; @Column(name="status",nullable=false) private String status="OPEN"; @Column(name="quantity") private Integer quantity; @Column(name="source_location") private String sourceLocation; @Column(name="destination_location") private String destinationLocation; @Column(name="assigned_to") private String assignedTo; @Column(name="due_at") private Instant dueAt; @Column(name="completed_at") private Instant completedAt; @Column(name="notes",columnDefinition="text") private String notes; @Column(name="created_at",nullable=false) private Instant createdAt=Instant.now();
 protected WarehouseTask(){}
 public WarehouseTask(UUID t,UUID w,UUID s,UUID item,String type,Integer qty,String source,String dest,String assigned,Instant due,String notes){tenantId=t;warehouseId=w;shipmentId=s;inventoryItemId=item;taskType=type;quantity=qty;sourceLocation=source;destinationLocation=dest;assignedTo=assigned;dueAt=due;this.notes=notes;}
 public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getWarehouseId(){return warehouseId;} public UUID getShipmentId(){return shipmentId;} public UUID getInventoryItemId(){return inventoryItemId;} public String getTaskType(){return taskType;} public String getStatus(){return status;} public Integer getQuantity(){return quantity;} public String getSourceLocation(){return sourceLocation;} public String getDestinationLocation(){return destinationLocation;} public String getAssignedTo(){return assignedTo;} public Instant getDueAt(){return dueAt;} public Instant getCompletedAt(){return completedAt;} public String getNotes(){return notes;} public Instant getCreatedAt(){return createdAt;}
 public void start(){if(!"OPEN".equals(status))throw new IllegalStateException("Warehouse task is not OPEN");status="IN_PROGRESS";} public void complete(){if("COMPLETED".equals(status))return;status="COMPLETED";completedAt=Instant.now();} public void cancel(){status="CANCELLED";}
}
