"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import {
  shipmentsApi,
  sensorsApi,
  downloadAwbPdf,
  flightStatusApi,
  Shipment,
  TrackingEvent,
  SensorReading,
  NotificationRecord,
  FlightStatusResult,
  ApiError,
} from "@/lib/api-client";
import { useAuth } from "@/lib/auth-context";

// Workflow status events are generated by validated state transitions. Manual
// timeline entries are restricted to exceptions so the displayed history cannot
// claim a departure/delivery that the shipment state machine never recorded.
const EVENT_TYPES = ["EXCEPTION"];

export default function ShipmentTrackingPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const { accessToken, isLoading } = useAuth();
  const [events, setEvents] = useState<TrackingEvent[]>([]);
  const [shipment, setShipment] = useState<Shipment | null>(null);
  const [copied, setCopied] = useState(false);
  const [readings, setReadings] = useState<SensorReading[]>([]);
  const [readingForm, setReadingForm] = useState({
    temperatureCelsius: "",
    humidityPercent: "",
  });
  const [thresholdForm, setThresholdForm] = useState({
    minTemperatureCelsius: "",
    maxTemperatureCelsius: "",
  });
  const [weightKg, setWeightKg] = useState("");
  const [notificationEmail, setNotificationEmail] = useState("");
  const [notifications, setNotifications] = useState<NotificationRecord[]>([]);
  const [flightNumber, setFlightNumber] = useState("");
  const [flightStatus, setFlightStatus] = useState<FlightStatusResult | null>(
    null,
  );
  const [flightStatusError, setFlightStatusError] = useState<string | null>(
    null,
  );
  const [downloadingAwb, setDownloadingAwb] = useState(false);
  const [form, setForm] = useState({
    eventType: "EXCEPTION",
    location: "",
    notes: "",
  });
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!isLoading && !accessToken) router.push("/login");
  }, [isLoading, accessToken, router]);

  useEffect(() => {
    if (accessToken) refresh();
  }, [accessToken]);

  async function refresh() {
    try {
      const [s, events, readings, notifications] = await Promise.all([
        shipmentsApi.get(params.id),
        shipmentsApi.trackingHistory(params.id),
        sensorsApi.history(params.id),
        shipmentsApi.notificationHistory(params.id),
      ]);
      setShipment(s);
      setWeightKg(s.weightKg != null ? String(s.weightKg) : "");
      setNotificationEmail(s.notificationEmail ?? "");
      setFlightNumber(s.flightNumber ?? "");
      setEvents(events);
      setReadings(readings.content);
      setNotifications(notifications.content);
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.message
          : "Failed to load tracking history",
      );
    }
  }

  async function saveWeight(e: React.FormEvent) {
    e.preventDefault();
    try {
      await shipmentsApi.updateWeight(params.id, Number(weightKg));
      refresh();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to save weight");
    }
  }

  async function saveNotificationEmail(e: React.FormEvent) {
    e.preventDefault();
    try {
      await shipmentsApi.updateNotificationEmail(params.id, notificationEmail);
      refresh();
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.message
          : "Failed to save notification email",
      );
    }
  }

  async function saveFlightNumber(e: React.FormEvent) {
    e.preventDefault();
    try {
      await shipmentsApi.updateFlightNumber(params.id, flightNumber);
      refresh();
    } catch (err) {
      setError(
        err instanceof ApiError ? err.message : "Failed to save flight number",
      );
    }
  }

  async function checkFlightStatus() {
    setFlightStatusError(null);
    const number = flightNumber.trim().toUpperCase();
    if (!number) {
      setFlightStatusError("Enter a flight number first.");
      return;
    }
    try {
      // Persist the value currently shown in the form before asking the backend
      // for status. This prevents a common race where the user types KQ100 and
      // immediately clicks Check status while the shipment still has no flight.
      if (shipment?.flightNumber?.trim().toUpperCase() !== number) {
        const updated = await shipmentsApi.updateFlightNumber(
          params.id,
          number,
        );
        setShipment(updated);
        setFlightNumber(updated.flightNumber ?? number);
      }
      setFlightStatus(await flightStatusApi.check(params.id));
      await refresh();
    } catch (err) {
      setFlightStatusError(
        err instanceof ApiError ? err.message : "Flight status check failed",
      );
    }
  }

  async function handleAwbDownload() {
    if (!shipment) return;
    setDownloadingAwb(true);
    try {
      await downloadAwbPdf(shipment.id);
    } catch (err) {
      setError(
        err instanceof ApiError ? err.message : "Unable to download AWB PDF",
      );
    } finally {
      setDownloadingAwb(false);
    }
  }

  async function submitReading(e: React.FormEvent) {
    e.preventDefault();
    try {
      await sensorsApi.recordReading(params.id, {
        temperatureCelsius: readingForm.temperatureCelsius
          ? Number(readingForm.temperatureCelsius)
          : undefined,
        humidityPercent: readingForm.humidityPercent
          ? Number(readingForm.humidityPercent)
          : undefined,
      });
      setReadingForm({ temperatureCelsius: "", humidityPercent: "" });
      refresh();
    } catch (err) {
      setError(
        err instanceof ApiError ? err.message : "Failed to record reading",
      );
    }
  }

  async function saveThreshold(e: React.FormEvent) {
    e.preventDefault();
    try {
      await sensorsApi.setThreshold(params.id, {
        minTemperatureCelsius: thresholdForm.minTemperatureCelsius
          ? Number(thresholdForm.minTemperatureCelsius)
          : undefined,
        maxTemperatureCelsius: thresholdForm.maxTemperatureCelsius
          ? Number(thresholdForm.maxTemperatureCelsius)
          : undefined,
      });
    } catch (err) {
      setError(
        err instanceof ApiError ? err.message : "Failed to save threshold",
      );
    }
  }

  function copyShareLink() {
    if (!shipment) return;
    const url = `${window.location.origin}/track/${shipment.trackingToken}`;
    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    try {
      await shipmentsApi.addTrackingEvent(params.id, form);
      setForm({ ...form, location: "", notes: "" });
      refresh();
    } catch (err) {
      setError(
        err instanceof ApiError ? err.message : "Failed to add tracking event",
      );
    }
  }

  if (isLoading || !accessToken) return null;

  const statusLabel = shipment?.status
    ? shipment.status.replace(/_/g, " ")
    : "LOADING";
  const etaLabel = shipment?.eta
    ? new Date(shipment.eta).toLocaleString()
    : "Not scheduled";
  const etdLabel = shipment?.etd
    ? new Date(shipment.etd).toLocaleString()
    : "Not scheduled";

  return (
    <main className="page">
      <div className="page-head">
        <div>
          <div className="eyebrow">AAL / SHIPMENT 360</div>
          <h1 className="page-title">
            {shipment?.referenceCode || "Shipment"}
          </h1>
          <p className="page-subtitle">
            One operational record for cargo, flight, documents, tracking and
            customer delivery.
          </p>
        </div>

        <div className="actions">
          <Link className="btn" href="/shipments">
            ← Shipment register
          </Link>
          <Link className="btn" href="/air-cargo">
            Air cargo
          </Link>
          {shipment && (
            <button
              className="btn btn-primary"
              type="button"
              onClick={handleAwbDownload}
              disabled={downloadingAwb}
            >
              {downloadingAwb ? "Preparing AWB…" : "Download AWB PDF"}
            </button>
          )}
        </div>
      </div>

      {error && <div className="alert alert-error">{error}</div>}

      {shipment && (
        <>
          <section
            className="card"
            style={{
              marginTop: 14,
              padding: 22,
              background:
                "linear-gradient(135deg, var(--aal-navy-950), var(--aal-navy-800))",
              color: "#fff",
              border: "1px solid rgba(255,255,255,.08)",
            }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                gap: 20,
                flexWrap: "wrap",
                alignItems: "flex-start",
              }}
            >
              <div>
                <div
                  style={{
                    fontSize: 11,
                    fontWeight: 800,
                    letterSpacing: ".12em",
                    opacity: 0.7,
                  }}
                >
                  OPERATIONAL SHIPMENT
                </div>
                <h2 style={{ margin: "7px 0 6px", fontSize: 28 }}>
                  {shipment.referenceCode}
                </h2>
                <div style={{ opacity: 0.78, fontSize: 13 }}>
                  {shipment.originCityPort || shipment.originAddress}{" "}
                  <span style={{ opacity: 0.55 }}>→</span>{" "}
                  {shipment.destinationCityPort || shipment.destinationAddress}
                </div>
              </div>

              <div
                style={{
                  padding: "9px 13px",
                  borderRadius: 999,
                  background: "rgba(255,255,255,.11)",
                  border: "1px solid rgba(255,255,255,.16)",
                  fontSize: 12,
                  fontWeight: 800,
                  letterSpacing: ".04em",
                }}
              >
                {statusLabel}
              </div>
            </div>

            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))",
                gap: 10,
                marginTop: 20,
              }}
            >
              {[
                ["Client", shipment.clientName || "—"],
                ["Mode", shipment.transportMode || "—"],
                ["Flight", shipment.flightNumber || "Not assigned"],
                ["Invoice", shipment.invoiceNo || "Generated / pending"],
              ].map(([label, value]) => (
                <div
                  key={label}
                  style={{
                    padding: 12,
                    borderRadius: 10,
                    background: "rgba(255,255,255,.07)",
                    border: "1px solid rgba(255,255,255,.09)",
                  }}
                >
                  <div
                    style={{
                      fontSize: 10,
                      textTransform: "uppercase",
                      letterSpacing: ".08em",
                      opacity: 0.58,
                    }}
                  >
                    {label}
                  </div>
                  <strong style={{ display: "block", marginTop: 4 }}>
                    {value}
                  </strong>
                </div>
              ))}
            </div>
          </section>

          <div className="grid grid-4" style={{ marginTop: 14 }}>
            {[
              ["Client revenue", shipment.amountBilledToClient],
              ["Total cost", shipment.totalCost],
              ["Gross profit", shipment.grossProfit],
              ["Receivable", shipment.amountRemaining],
            ].map(([label, value]) => (
              <div className="kpi" key={String(label)}>
                <div className="kpi-label">{label}</div>
                <div className="kpi-value" style={{ fontSize: 19 }}>
                  {typeof value === "number" ? value.toLocaleString() : "—"}{" "}
                  {shipment.currency || ""}
                </div>
              </div>
            ))}
          </div>

          <div className="grid grid-2" style={{ marginTop: 14 }}>
            <section className="card">
              <div className="page-head" style={{ marginBottom: 12 }}>
                <div>
                  <h2 className="card-title">Flight & ETA</h2>
                  <div className="card-muted">
                    Scheduled milestones remain visible even when no live
                    airline feed is configured.
                  </div>
                </div>
                <span className="status status-neutral">
                  {flightStatus?.flightStatus || "SCHEDULED"}
                </span>
              </div>

              <div className="grid grid-2">
                <div className="kpi">
                  <div className="kpi-label">Flight number</div>
                  <div className="kpi-value" style={{ fontSize: 18 }}>
                    {shipment.flightNumber || "Not assigned"}
                  </div>
                </div>
                <div className="kpi">
                  <div className="kpi-label">ETA</div>
                  <div className="kpi-value" style={{ fontSize: 16 }}>
                    {etaLabel}
                  </div>
                </div>
              </div>

              <form
                onSubmit={saveFlightNumber}
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr auto auto",
                  gap: 8,
                  marginTop: 12,
                }}
              >
                <input
                  aria-label="Flight number"
                  placeholder="KQ100"
                  value={flightNumber}
                  onChange={(e) => setFlightNumber(e.target.value)}
                />
                <button
                  className="btn"
                  type="submit"
                  disabled={!flightNumber.trim()}
                >
                  Save
                </button>
                <button
                  className="btn btn-primary"
                  type="button"
                  onClick={checkFlightStatus}
                  disabled={!flightNumber.trim()}
                >
                  Check status
                </button>
              </form>

              <div className="card-muted" style={{ marginTop: 10 }}>
                ETD: {etdLabel}
              </div>

              {flightStatusError && (
                <div className="alert alert-error" style={{ marginTop: 10 }}>
                  {flightStatusError}
                </div>
              )}

              {flightStatus && (
                <div
                  className="alert"
                  style={{
                    marginTop: 10,
                    borderColor: flightStatus.significantDelay
                      ? "rgba(180,71,8,.22)"
                      : "rgba(8,116,67,.22)",
                  }}
                >
                  Status: <strong>{flightStatus.flightStatus}</strong> ·
                  departure +{flightStatus.departureDelayMinutes} min · arrival
                  +{flightStatus.arrivalDelayMinutes} min
                </div>
              )}
            </section>

            <section className="card">
              <div className="page-head" style={{ marginBottom: 12 }}>
                <div>
                  <h2 className="card-title">Customer & access</h2>
                  <div className="card-muted">
                    Keep the customer-facing tracking link separate from the
                    internal control workspace.
                  </div>
                </div>
              </div>

              <div className="field">
                <label>Notification email</label>
                <input
                  type="email"
                  placeholder="customer@example.com"
                  value={notificationEmail}
                  onChange={(e) => setNotificationEmail(e.target.value)}
                />
              </div>

              <div className="actions" style={{ marginTop: 10 }}>
                <button
                  className="btn"
                  type="button"
                  onClick={async () => {
                    try {
                      await shipmentsApi.updateNotificationEmail(
                        params.id,
                        notificationEmail,
                      );
                      await refresh();
                    } catch (err) {
                      setError(
                        err instanceof ApiError
                          ? err.message
                          : "Failed to save notification email",
                      );
                    }
                  }}
                >
                  Save email
                </button>
                <button className="btn" type="button" onClick={copyShareLink}>
                  {copied ? "Link copied" : "Copy customer tracking link"}
                </button>
              </div>
            </section>
          </div>

          <div className="grid grid-2" style={{ marginTop: 14 }}>
            <section className="card">
              <div className="page-head" style={{ marginBottom: 10 }}>
                <div>
                  <h2 className="card-title">Tracking timeline</h2>
                  <div className="card-muted">
                    Operational events from booking through delivery.
                  </div>
                </div>
              </div>

              <form
                onSubmit={handleSubmit}
                style={{
                  display: "grid",
                  gridTemplateColumns: "160px 1fr 1fr auto",
                  gap: 8,
                  marginBottom: 16,
                }}
              >
                <select
                  value={form.eventType}
                  onChange={(e) =>
                    setForm({ ...form, eventType: e.target.value })
                  }
                >
                  {EVENT_TYPES.map((t) => (
                    <option key={t} value={t}>
                      {t.replace(/_/g, " ")}
                    </option>
                  ))}
                </select>
                <input
                  placeholder="Location"
                  value={form.location}
                  onChange={(e) =>
                    setForm({ ...form, location: e.target.value })
                  }
                />
                <input
                  placeholder="Operational note"
                  value={form.notes}
                  onChange={(e) => setForm({ ...form, notes: e.target.value })}
                />
                <button className="btn btn-primary" type="submit">
                  Add event
                </button>
              </form>

              <ol
                style={{
                  listStyle: "none",
                  margin: 0,
                  padding: 0,
                  borderLeft: "2px solid var(--aal-line)",
                }}
              >
                {events.map((ev) => (
                  <li
                    key={ev.id}
                    style={{
                      position: "relative",
                      padding: "0 0 16px 18px",
                      marginLeft: 0,
                    }}
                  >
                    <span
                      style={{
                        position: "absolute",
                        left: -7,
                        top: 3,
                        width: 12,
                        height: 12,
                        borderRadius: "50%",
                        background:
                          ev.eventType === "EXCEPTION"
                            ? "var(--aal-danger)"
                            : "var(--aal-blue)",
                        boxShadow: "0 0 0 4px var(--aal-panel)",
                      }}
                    />
                    <strong>{ev.eventType.replace(/_/g, " ")}</strong>
                    <div className="card-muted">
                      {new Date(ev.occurredAt).toLocaleString()}
                      {ev.location ? ` · ${ev.location}` : ""}
                    </div>
                    {ev.notes && <div style={{ marginTop: 3 }}>{ev.notes}</div>}
                  </li>
                ))}
                {!events.length && (
                  <li style={{ paddingLeft: 18 }} className="empty">
                    No tracking events yet.
                  </li>
                )}
              </ol>
            </section>

            <section className="card">
              <div className="page-head" style={{ marginBottom: 10 }}>
                <div>
                  <h2 className="card-title">Operations</h2>
                  <div className="card-muted">
                    Documents, billing, dispatch and cold-chain controls.
                  </div>
                </div>
              </div>

              <div className="grid grid-2">
                <Link className="btn" href="/documents">
                  Documents & customs
                </Link>
                <Link className="btn" href="/billing">
                  Invoice & payment
                </Link>
                <Link className="btn" href="/trips">
                  Dispatch / POD
                </Link>
                <button
                  className="btn btn-primary"
                  type="button"
                  onClick={handleAwbDownload}
                  disabled={downloadingAwb}
                >
                  {downloadingAwb ? "Preparing…" : "Download AWB"}
                </button>
              </div>

              <div className="section-heading" style={{ marginTop: 18 }}>
                <div className="section-number">COLD</div>
                <div>
                  <h3 style={{ margin: 0 }}>Cold-chain monitoring</h3>
                  <p className="card-muted">
                    Record sensor readings and monitor exceptions for sensitive
                    cargo.
                  </p>
                </div>
              </div>

              <form
                onSubmit={submitReading}
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr auto",
                  gap: 8,
                }}
              >
                <input
                  placeholder="Temperature °C"
                  value={readingForm.temperatureCelsius}
                  onChange={(e) =>
                    setReadingForm({
                      ...readingForm,
                      temperatureCelsius: e.target.value,
                    })
                  }
                />
                <input
                  placeholder="Humidity %"
                  value={readingForm.humidityPercent}
                  onChange={(e) =>
                    setReadingForm({
                      ...readingForm,
                      humidityPercent: e.target.value,
                    })
                  }
                />
                <button className="btn" type="submit">
                  Log reading
                </button>
              </form>

              <div className="table-wrap" style={{ marginTop: 12 }}>
                <table className="table">
                  <thead>
                    <tr>
                      <th>Temperature</th>
                      <th>Humidity</th>
                      <th>When</th>
                    </tr>
                  </thead>
                  <tbody>
                    {readings.slice(0, 5).map((r) => (
                      <tr key={r.id}>
                        <td>
                          {r.temperatureCelsius != null
                            ? `${r.temperatureCelsius}°C`
                            : "—"}
                        </td>
                        <td>
                          {r.humidityPercent != null
                            ? `${r.humidityPercent}%`
                            : "—"}
                        </td>
                        <td>{new Date(r.recordedAt).toLocaleString()}</td>
                      </tr>
                    ))}
                    {!readings.length && (
                      <tr>
                        <td colSpan={3} className="empty">
                          No sensor readings yet.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </section>
          </div>

          <section className="card" style={{ marginTop: 14 }}>
            <div className="page-head" style={{ marginBottom: 10 }}>
              <div>
                <h2 className="card-title">Notification log</h2>
                <div className="card-muted">
                  Customer and operations notifications generated from shipment
                  events.
                </div>
              </div>
              <span className="status status-neutral">
                {notifications.length} records
              </span>
            </div>
            <div className="table-wrap">
              <table className="table">
                <thead>
                  <tr>
                    <th>Status</th>
                    <th>Recipient</th>
                    <th>Subject</th>
                    <th>When</th>
                  </tr>
                </thead>
                <tbody>
                  {notifications.map((n) => (
                    <tr key={n.id}>
                      <td>{n.status.replace(/_/g, " ")}</td>
                      <td>{n.recipient || "—"}</td>
                      <td>{n.subject}</td>
                      <td>{new Date(n.createdAt).toLocaleString()}</td>
                    </tr>
                  ))}
                  {!notifications.length && (
                    <tr>
                      <td colSpan={4} className="empty">
                        No notifications yet.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}

      {!shipment && !error && (
        <section className="card empty" style={{ marginTop: 14, padding: 40 }}>
          Loading shipment…
        </section>
      )}
    </main>
  );
}
