package com.logiplatform.service;
import com.logiplatform.dto.JourneyDtos.*; import com.logiplatform.tenancy.TenantContext; import org.springframework.beans.factory.annotation.Qualifier; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import java.time.Instant; import java.util.*;
@Service public class JourneyService { private final JdbcTemplate db; public JourneyService(@Qualifier("tenantJdbcTemplate") JdbcTemplate db){this.db=db;}
 public Journey get(UUID shipmentId){UUID t=TenantContext.getTenantId(); if(db.queryForObject("SELECT count(*) FROM shipments WHERE id=? AND tenant_id=?",Integer.class,shipmentId,t)==0) throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"Shipment not found");
  List<Leg> legs=db.query("SELECT id,sequence_no,mode,origin,destination,carrier_name,carrier_reference,planned_departure,planned_arrival,actual_departure,actual_arrival,status FROM transport_legs WHERE shipment_id=? AND tenant_id=? ORDER BY sequence_no",(rs,n)->{UUID id=rs.getObject(1,UUID.class); return new Leg(id,rs.getInt(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),ts(rs,8),ts(rs,9),ts(rs,10),ts(rs,11),rs.getString(12),milestones(id),costs(id),documents(id));},shipmentId,t);
  Instant eta=legs.stream().map(Leg::eta).filter(Objects::nonNull).max(Comparator.naturalOrder()).orElse(null); String status=db.queryForObject("SELECT status FROM shipments WHERE id=? AND tenant_id=?",String.class,shipmentId,t); return new Journey(shipmentId,legs,eta,status);
 }
 private Instant ts(java.sql.ResultSet r,int i)throws java.sql.SQLException{return r.getTimestamp(i)==null?null:r.getTimestamp(i).toInstant();}
 private List<Milestone> milestones(UUID id){return db.query("SELECT id,milestone_type,location,planned_at,actual_at,status,notes FROM transport_leg_milestones WHERE leg_id=? AND tenant_id=? ORDER BY COALESCE(actual_at,planned_at),created_at",(r,n)->new Milestone(r.getObject(1,UUID.class),r.getString(2),r.getString(3),ts(r,4),ts(r,5),r.getString(6),r.getString(7)),id,TenantContext.getTenantId());}
 private List<Cost> costs(UUID id){return db.query("SELECT id,description,amount,currency,supplier FROM transport_leg_costs WHERE leg_id=? AND tenant_id=? ORDER BY created_at",(r,n)->new Cost(r.getObject(1,UUID.class),r.getString(2),r.getBigDecimal(3),r.getString(4),r.getString(5)),id,TenantContext.getTenantId());}
 private List<Document> documents(UUID id){return db.query("SELECT id,document_type,document_uri,customer_visible,status FROM transport_leg_documents WHERE leg_id=? AND tenant_id=? ORDER BY created_at",(r,n)->new Document(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getBoolean(4),r.getString(5)),id,TenantContext.getTenantId());}
}
