"use client";
import { useEffect, useState } from "react";
import { platformApi, PlatformFxRate, PlatformPeriod, PlatformAdjustment, PlatformGeofence, PlatformIntegration } from "@/lib/api-client";
import { useAuth } from "@/lib/auth-context";
import Link from "next/link";

export default function PlatformPage(){
 const {role}=useAuth(); const [fx,setFx]=useState<PlatformFxRate[]>([]),[periods,setPeriods]=useState<PlatformPeriod[]>([]),[adjustments,setAdjustments]=useState<PlatformAdjustment[]>([]),[geofences,setGeofences]=useState<PlatformGeofence[]>([]),[integrations,setIntegrations]=useState<PlatformIntegration[]>([]),[msg,setMsg]=useState("");
 useEffect(()=>{ Promise.all([platformApi.fxRates(new Date(new Date().getFullYear(),0,1).toISOString().slice(0,10),new Date().toISOString().slice(0,10)),platformApi.periods(),platformApi.adjustments(),platformApi.geofences(),platformApi.integrations()]).then(([a,b,c,d,e])=>{setFx(a);setPeriods(b);setAdjustments(c);setGeofences(d);setIntegrations(e)}).catch(e=>setMsg(e?.message||"Unable to load platform controls"));},[]);
 async function addFx(){try{const r=await platformApi.upsertFx({rateDate:new Date().toISOString().slice(0,10),baseCurrency:"USD",quoteCurrency:"RWF",rate:1450,source:"AAL manual"});setFx(x=>[r,...x.filter(v=>v.id!==r.id)]);setMsg("FX rate saved")}catch(e:any){setMsg(e.message)}}
 async function addPeriod(){try{const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10),end=new Date(now.getFullYear(),now.getMonth()+1,0).toISOString().slice(0,10);const r=await platformApi.openPeriod({periodStart:start,periodEnd:end,notes:"AAL operating period"});setPeriods(x=>[r,...x]);setMsg("Financial period opened")}catch(e:any){setMsg(e.message)}}
 async function addGeo(){try{const r=await platformApi.createGeofence({name:`AAL Hub ${geofences.length+1}`,latitude:-1.9441,longitude:30.0619,radiusM:1000});setGeofences(x=>[...x,r]);setMsg("Geofence created")}catch(e:any){setMsg(e.message)}}
 if(!["ADMIN","MANAGER","FINANCE","OPERATIONS"].includes(role||"")) return <main className="page"><div className="card">Access denied.</div></main>;
 return <main className="page"><div className="page-head"><div><div className="eyebrow">AAL ADVANCED CONTROLS</div><h1 className="page-title">Platform controls</h1><p className="page-subtitle">Advanced finance, security, geofencing and integration controls. General configuration is maintained in Settings.</p></div><Link className="btn btn-primary" href="/settings">Open Settings</Link></div>{msg&&<div className="alert alert-info" style={{marginBottom:16}}>{msg}</div>}<div className="grid grid-2"><section className="card"><h2 className="card-title">FX rates</h2><button className="btn btn-primary" onClick={addFx}>Save USD/RWF rate</button>{fx.slice(0,8).map(x=><div className="portal-list-row" key={x.id}><span>{x.rateDate} · {x.baseCurrency}/{x.quoteCurrency}</span><strong>{x.rate}</strong></div>)}</section><section className="card"><h2 className="card-title">Financial periods</h2><button className="btn btn-primary" onClick={addPeriod}>Open current period</button>{periods.slice(0,8).map(x=><div className="portal-list-row" key={x.id}><span>{x.periodStart} → {x.periodEnd}</span><strong>{x.status}</strong></div>)}</section><section className="card"><h2 className="card-title">Credit / debit notes</h2>{adjustments.slice(0,8).map(x=><div className="portal-list-row" key={x.id}><span>{x.adjustmentNo} · {x.adjustmentType}</span><strong>{x.currency} {x.amount}</strong></div>)}{!adjustments.length&&<p className="page-subtitle">No adjustments recorded.</p>}</section><section className="card"><h2 className="card-title">Geofences</h2><button className="btn btn-primary" onClick={addGeo}>Create AAL geofence</button>{geofences.map(x=><div className="portal-list-row" key={x.id}><span>{x.name}</span><strong>{x.radiusM} m</strong></div>)}</section><section className="card" style={{gridColumn:"1 / -1"}}><h2 className="card-title">Integration registry</h2><div className="table-wrap"><table className="table"><thead><tr><th>Integration</th><th>Protocol</th><th>Enabled</th><th>Health</th><th>Last failure</th></tr></thead><tbody>{integrations.map(x=><tr key={x.id}><td><strong>{x.displayName}</strong><div>{x.code}</div></td><td>{x.protocol}</td><td>{x.enabled?"YES":"NO"}</td><td>{x.healthStatus}</td><td>{x.lastError||"—"}</td></tr>)}</tbody></table></div></section></div></main>
}
