package com.logiplatform.controller;
import com.logiplatform.dto.AuthDtos.*; import com.logiplatform.security.TenantPrincipal; import com.logiplatform.service.AuthService;
import jakarta.validation.Valid; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.security.SecureRandom; import java.time.Duration; import java.util.HexFormat;
@RestController @RequestMapping("/api/auth")
public class AuthController{
 private static final String SESSION_COOKIE="NLS_SESSION",CSRF_COOKIE="NLS_CSRF"; private final SecureRandom random=new SecureRandom(); private final AuthService authService;
 @Value("${app.environment:development}") private String environment;
 public AuthController(AuthService authService){this.authService=authService;}
 @PostMapping("/login") public ResponseEntity<AuthResponse> login(@Valid @RequestBody LoginRequest request){AuthResponse r=authService.login(request); if(r.accessToken()==null)return ResponseEntity.ok(r);return withSession(r);}
 @PatchMapping("/change-password") public ResponseEntity<Void> changePassword(@RequestBody ChangePasswordRequest r, Authentication a){ if(a==null||!(a.getPrincipal() instanceof TenantPrincipal p)) return ResponseEntity.status(401).build(); authService.changeOwnPassword(p.userId(),r.currentPassword(),r.newPassword()); return ResponseEntity.noContent().build(); }
 @PostMapping("/send-login-otp") public ResponseEntity<Void> sendLoginOtp(@Valid @RequestBody LoginOtpRequest request){authService.sendLoginOtp(request.otpChallengeToken());return ResponseEntity.noContent().build();}
 @GetMapping("/csrf") public ResponseEntity<CsrfResponse> csrf(@CookieValue(name=CSRF_COOKIE,required=false) String existing){String token=existing!=null&&existing.length()==64&&isHex(existing)?existing:newCsrf(); ResponseCookie c=ResponseCookie.from(CSRF_COOKIE,token).httpOnly(false).secure(isProduction()).sameSite(isProduction()?"None":"Lax").path("/").maxAge(Duration.ofHours(8)).build();return ResponseEntity.ok().header("Set-Cookie",c.toString()).body(new CsrfResponse(token));}
 @GetMapping("/session") public ResponseEntity<SessionResponse> session(Authentication a){if(a==null||!a.isAuthenticated()||!(a.getPrincipal() instanceof TenantPrincipal p))return ResponseEntity.status(401).build();boolean mustChange=authService.mustChangePassword(p.userId()); return ResponseEntity.ok(new SessionResponse(p.tenantId().toString(),p.userId().toString(),p.role(),mustChange));}
 @PostMapping("/logout") public ResponseEntity<Void> logout(Authentication a){if(a!=null&&a.isAuthenticated()&&a.getPrincipal() instanceof TenantPrincipal p)authService.logout(p.userId());ResponseCookie s=ResponseCookie.from(SESSION_COOKIE,"").httpOnly(true).secure(isProduction()).sameSite(isProduction()?"None":"Lax").path("/").maxAge(Duration.ZERO).build();ResponseCookie c=ResponseCookie.from(CSRF_COOKIE,"").httpOnly(false).secure(isProduction()).sameSite(isProduction()?"None":"Lax").path("/").maxAge(Duration.ZERO).build();return ResponseEntity.noContent().header("Set-Cookie",s.toString()).header("Set-Cookie",c.toString()).build();}
 private ResponseEntity<AuthResponse> withSession(AuthResponse r){ResponseCookie c=ResponseCookie.from(SESSION_COOKIE,r.accessToken()).httpOnly(true).secure(isProduction()).sameSite(isProduction()?"None":"Lax").path("/").maxAge(Duration.ofHours(1)).build();return ResponseEntity.ok().header("Set-Cookie",c.toString()).body(r);}
 private boolean isProduction(){return "production".equalsIgnoreCase(environment);} private String newCsrf(){byte[] b=new byte[32];random.nextBytes(b);return HexFormat.of().formatHex(b);} private boolean isHex(String v){for(char c:v.toCharArray())if(!Character.toString(c).matches("[0-9a-fA-F]"))return false;return true;}
 public record SessionResponse(String tenantId,String userId,String role,boolean mustChangePassword){} public record CsrfResponse(String token){} public record ChangePasswordRequest(String currentPassword,String newPassword){}
}
