package com.logiplatform.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.logiplatform.service.ExternalGatewayService;
import com.logiplatform.tenancy.TenantContext;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.time.*;
import java.util.*;

@RestController
@RequestMapping("/api/platform/enterprise")
public class EnterprisePlatformController {
    private final JdbcTemplate db; private final ExternalGatewayService gateway; private final ObjectMapper mapper;
    public EnterprisePlatformController(@Qualifier("tenantJdbcTemplate") JdbcTemplate db, ExternalGatewayService gateway, ObjectMapper mapper){this.db=db;this.gateway=gateway;this.mapper=mapper;}
    private UUID t(){return TenantContext.getTenantId();}

    @GetMapping("/carriers") public List<Map<String,Object>> carriers(){return db.queryForList("select id,carrier_code as \"carrierCode\",carrier_name as \"carrierName\",mode,scac_iata_code as \"scacIataCode\",api_integration_code as \"apiIntegrationCode\",contact_email as \"contactEmail\",country_code as \"countryCode\",active,metadata_json as \"metadataJson\" from carrier_master where tenant_id=? order by carrier_name",t());}
    @PostMapping("/carriers") public Map<String,Object> carrier(@Valid @RequestBody CarrierRequest r){UUID id=UUID.randomUUID();db.update("insert into carrier_master(id,tenant_id,carrier_code,carrier_name,mode,scac_iata_code,api_integration_code,contact_email,country_code,active,metadata_json) values(?,?,?,?,?,?,?,?,?,?,?) on conflict(tenant_id,carrier_code) do update set carrier_name=excluded.carrier_name,mode=excluded.mode,scac_iata_code=excluded.scac_iata_code,api_integration_code=excluded.api_integration_code,contact_email=excluded.contact_email,country_code=excluded.country_code,active=excluded.active,metadata_json=excluded.metadata_json,updated_at=now()",id,t(),r.code(),r.name(),r.mode(),r.scacIataCode(),r.integrationCode(),r.contactEmail(),r.countryCode(),r.active(),r.metadataJson());return Map.of("id",id,"carrierCode",r.code());}
    @GetMapping("/lanes") public List<Map<String,Object>> lanes(){return db.queryForList("select id,lane_code as \"laneCode\",origin_code as \"originCode\",destination_code as \"destinationCode\",mode,default_transit_minutes as \"defaultTransitMinutes\",active from lane_master where tenant_id=? order by lane_code",t());}
    @PostMapping("/lanes") public Map<String,Object> lane(@Valid @RequestBody LaneRequest r){UUID id=UUID.randomUUID();db.update("insert into lane_master(id,tenant_id,lane_code,origin_code,destination_code,mode,default_transit_minutes,active) values(?,?,?,?,?,?,?,?) on conflict(tenant_id,lane_code) do update set origin_code=excluded.origin_code,destination_code=excluded.destination_code,mode=excluded.mode,default_transit_minutes=excluded.default_transit_minutes,active=excluded.active",id,t(),r.code(),r.origin(),r.destination(),r.mode(),r.transitMinutes(),r.active());return Map.of("id",id,"laneCode",r.code());}
    @GetMapping("/locations") public List<Map<String,Object>> locations(){return db.queryForList("select id,location_code as \"locationCode\",location_type as \"locationType\",name,city,country_code as \"countryCode\",latitude,longitude,timezone,active from location_master where tenant_id=? order by name",t());}
    @PostMapping("/locations") public Map<String,Object> location(@Valid @RequestBody LocationRequest r){UUID id=UUID.randomUUID();db.update("insert into location_master(id,tenant_id,location_code,location_type,name,city,country_code,latitude,longitude,timezone,active,metadata_json) values(?,?,?,?,?,?,?,?,?,?,?,?) on conflict(tenant_id,location_code) do update set location_type=excluded.location_type,name=excluded.name,city=excluded.city,country_code=excluded.country_code,latitude=excluded.latitude,longitude=excluded.longitude,timezone=excluded.timezone,active=excluded.active,metadata_json=excluded.metadata_json",id,t(),r.code(),r.type(),r.name(),r.city(),r.countryCode(),r.latitude(),r.longitude(),r.timezone(),r.active(),r.metadataJson());return Map.of("id",id,"locationCode",r.code());}

    @GetMapping("/pricing-rules") public List<Map<String,Object>> pricingRules(){return db.queryForList("select id,rule_code as \"ruleCode\",priority,mode,lane_code as \"laneCode\",customer_segment as \"customerSegment\",commodity_group as \"commodityGroup\",min_weight_kg as \"minWeightKg\",max_weight_kg as \"maxWeightKg\",min_charge as \"minCharge\",rate_per_kg as \"ratePerKg\",markup_percent as \"markupPercent\",fuel_percent as \"fuelPercent\",tax_percent as \"taxPercent\",currency,valid_from as \"validFrom\",valid_until as \"validUntil\",active,conditions_json as \"conditionsJson\" from pricing_rules where tenant_id=? order by priority,rule_code",t());}
    @PostMapping("/pricing-rules") public Map<String,Object> pricingRule(@Valid @RequestBody PricingRuleRequest r){UUID id=UUID.randomUUID();db.update("insert into pricing_rules(id,tenant_id,rule_code,priority,mode,lane_code,customer_segment,commodity_group,min_weight_kg,max_weight_kg,min_charge,rate_per_kg,markup_percent,fuel_percent,tax_percent,currency,valid_from,valid_until,active,conditions_json) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(tenant_id,rule_code) do update set priority=excluded.priority,mode=excluded.mode,lane_code=excluded.lane_code,customer_segment=excluded.customer_segment,commodity_group=excluded.commodity_group,min_weight_kg=excluded.min_weight_kg,max_weight_kg=excluded.max_weight_kg,min_charge=excluded.min_charge,rate_per_kg=excluded.rate_per_kg,markup_percent=excluded.markup_percent,fuel_percent=excluded.fuel_percent,tax_percent=excluded.tax_percent,currency=excluded.currency,valid_from=excluded.valid_from,valid_until=excluded.valid_until,active=excluded.active,conditions_json=excluded.conditions_json,updated_at=now()",id,t(),r.code(),r.priority(),r.mode(),r.laneCode(),r.customerSegment(),r.commodityGroup(),r.minWeightKg(),r.maxWeightKg(),r.minCharge(),r.ratePerKg(),r.markupPercent(),r.fuelPercent(),r.taxPercent(),r.currency(),r.validFrom(),r.validUntil(),r.active(),r.conditionsJson());return Map.of("id",id,"ruleCode",r.code());}
    @PostMapping("/pricing/quote") public Map<String,Object> price(@RequestBody PricingRequest r){
        UUID tenant=t(); LocalDate date=r.date()==null?LocalDate.now():r.date();
        List<Map<String,Object>> rules=db.queryForList("select * from pricing_rules where tenant_id=? and active=true and valid_from<=? and (valid_until is null or valid_until>=?) and (mode is null or upper(mode)=upper(?)) and (lane_code is null or upper(lane_code)=upper(?)) and (min_weight_kg is null or min_weight_kg<=?) and (max_weight_kg is null or max_weight_kg>=?) order by priority,rule_code",tenant,date,date,r.mode(),r.laneCode(),r.weightKg(),r.weightKg());
        if(rules.isEmpty()) throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"No commercial pricing rule matches the request");
        Map<String,Object> rule=rules.get(0); BigDecimal weight=r.weightKg()==null?BigDecimal.ZERO:r.weightKg(); BigDecimal rate=bd(rule.get("rate_per_kg")); BigDecimal min=bd(rule.get("min_charge")); BigDecimal base=weight.multiply(rate); if(base.compareTo(min)<0)base=min; BigDecimal fuel=base.multiply(bd(rule.get("fuel_percent"))).divide(BigDecimal.valueOf(100),2,java.math.RoundingMode.HALF_UP); BigDecimal markup=base.add(fuel).multiply(bd(rule.get("markup_percent"))).divide(BigDecimal.valueOf(100),2,java.math.RoundingMode.HALF_UP); BigDecimal tax=base.add(fuel).add(markup).multiply(bd(rule.get("tax_percent"))).divide(BigDecimal.valueOf(100),2,java.math.RoundingMode.HALF_UP); BigDecimal total=base.add(fuel).add(markup).add(tax); return Map.of("ruleCode",rule.get("rule_code"),"currency",rule.get("currency"),"base",base,"fuel",fuel,"markup",markup,"tax",tax,"total",total);
    }

    @PostMapping("/clients/{clientId}/convert-lead") public Map<String,Object> convertLead(@PathVariable UUID clientId){int n=db.update("update client_records set lifecycle_stage='CUSTOMER',client_status=COALESCE(NULLIF(client_status,''),'ACTIVE'),updated_at=now() where id=? and tenant_id=?",clientId,t());if(n!=1)throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"Client/lead not found");return Map.of("clientId",clientId,"lifecycleStage","CUSTOMER");}
    @GetMapping("/clients/{clientId}/activities") public List<Map<String,Object>> activities(@PathVariable UUID clientId){return db.queryForList("select id,activity_type as \"activityType\",subject,body,owner,due_at as \"dueAt\",completed_at as \"completedAt\",created_at as \"createdAt\" from crm_activities where tenant_id=? and client_id=? order by created_at desc",t(),clientId);}
    @PostMapping("/clients/{clientId}/activities") public Map<String,Object> activity(@PathVariable UUID clientId,@Valid @RequestBody ActivityRequest r){UUID id=UUID.randomUUID();db.update("insert into crm_activities(id,tenant_id,client_id,activity_type,subject,body,owner,due_at) values(?,?,?,?,?,?,?,?)",id,t(),clientId,r.type(),r.subject(),r.body(),r.owner(),r.dueAt());return Map.of("id",id,"status","OPEN");}

    @GetMapping("/notifications/preferences") public List<Map<String,Object>> notificationPreferences(){return db.queryForList("select id,client_id as \"clientId\",user_id as \"userId\",event_type as \"eventType\",email_enabled as \"emailEnabled\",sms_enabled as \"smsEnabled\",whatsapp_enabled as \"whatsappEnabled\",in_app_enabled as \"inAppEnabled\" from notification_preferences where tenant_id=? order by event_type",t());}
    @PostMapping("/notifications/preferences") public Map<String,Object> notificationPreference(@RequestBody Map<String,Object> r){UUID id=UUID.randomUUID();db.update("insert into notification_preferences(id,tenant_id,client_id,user_id,event_type,email_enabled,sms_enabled,whatsapp_enabled,in_app_enabled) values(?,?,?,?,?,?,?,?,?) on conflict(tenant_id,client_id,user_id,event_type) do update set email_enabled=excluded.email_enabled,sms_enabled=excluded.sms_enabled,whatsapp_enabled=excluded.whatsapp_enabled,in_app_enabled=excluded.in_app_enabled",id,t(),uuid(r.get("clientId")),uuid(r.get("userId")),String.valueOf(r.get("eventType")),bool(r,"emailEnabled",true),bool(r,"smsEnabled",false),bool(r,"whatsappEnabled",false),bool(r,"inAppEnabled",true));return Map.of("id",id);}
    @GetMapping("/notifications/templates") public List<Map<String,Object>> notificationTemplates(){return db.queryForList("select id,event_type as \"eventType\",channel,subject_template as \"subjectTemplate\",body_template as \"bodyTemplate\",active,version_no as \"versionNo\" from notification_templates where tenant_id=? order by event_type,channel,version_no desc",t());}
    @PostMapping("/notifications/templates") public Map<String,Object> notificationTemplate(@RequestBody Map<String,Object> r){UUID id=UUID.randomUUID();db.update("insert into notification_templates(id,tenant_id,event_type,channel,subject_template,body_template,active,version_no) values(?,?,?,?,?,?,?,?)",id,t(),String.valueOf(r.get("eventType")),String.valueOf(r.get("channel")),String.valueOf(r.getOrDefault("subjectTemplate","")),String.valueOf(r.get("bodyTemplate")),bool(r,"active",true),((Number)r.getOrDefault("versionNo",1)).intValue());return Map.of("id",id);}

    @GetMapping("/customs/workflows") public List<Map<String,Object>> customs(){return db.queryForList("select id,shipment_id as \"shipmentId\",declaration_id as \"declarationId\",stage,status,assigned_to as \"assignedTo\",due_at as \"dueAt\",completed_at as \"completedAt\",external_reference as \"externalReference\",notes from customs_workflows where tenant_id=? order by due_at nulls last,created_at desc",t());}
    @PostMapping("/customs/workflows") public Map<String,Object> customs(@Valid @RequestBody CustomsWorkflowRequest r){UUID id=UUID.randomUUID();db.update("insert into customs_workflows(id,tenant_id,shipment_id,declaration_id,stage,status,assigned_to,due_at,external_reference,notes) values(?,?,?,?,?,?,?,?,?,?)",id,t(),r.shipmentId(),r.declarationId(),r.stage(),r.status(),r.assignedTo(),r.dueAt(),r.externalReference(),r.notes());return Map.of("id",id,"status",r.status());}

    @PostMapping("/integrations/carrier/test") public Map<String,Object> carrierTest(@RequestBody Map<String,Object> payload){return gateway.submitBooking(payload);}
    @PostMapping("/integrations/customs/test") public Map<String,Object> customsTest(@RequestBody Map<String,Object> payload){return gateway.submitCustoms(payload);}

    private static BigDecimal bd(Object v){return v==null?BigDecimal.ZERO:new BigDecimal(v.toString());}
    private static UUID uuid(Object v){return v==null||v.toString().isBlank()?null:UUID.fromString(v.toString());}
    private static boolean bool(Map<String,Object> m,String k,boolean d){Object v=m.get(k);return v==null?d:Boolean.parseBoolean(v.toString());}
    public record CarrierRequest(@NotBlank String code,@NotBlank String name,@NotBlank String mode,String scacIataCode,String integrationCode,String contactEmail,String countryCode,boolean active,String metadataJson){}
    public record LaneRequest(@NotBlank String code,@NotBlank String origin,@NotBlank String destination,@NotBlank String mode,Integer transitMinutes,boolean active){}
    public record LocationRequest(@NotBlank String code,@NotBlank String type,@NotBlank String name,String city,String countryCode,Double latitude,Double longitude,String timezone,boolean active,String metadataJson){}
    public record PricingRuleRequest(@NotBlank String code,Integer priority,String mode,String laneCode,String customerSegment,String commodityGroup,BigDecimal minWeightKg,BigDecimal maxWeightKg,BigDecimal minCharge,BigDecimal ratePerKg,BigDecimal markupPercent,BigDecimal fuelPercent,BigDecimal taxPercent,@NotBlank String currency,@NotNull LocalDate validFrom,LocalDate validUntil,boolean active,String conditionsJson){}
    public record PricingRequest(String mode,String laneCode,BigDecimal weightKg,LocalDate date){}
    public record ActivityRequest(@NotBlank String type,@NotBlank String subject,String body,UUID owner,Instant dueAt){}
    public record CustomsWorkflowRequest(@NotNull UUID shipmentId,UUID declarationId,@NotBlank String stage,String status,UUID assignedTo,Instant dueAt,String externalReference,String notes){}
}
