package com.logiplatform.controller;
import com.logiplatform.dto.OperationsDtos.*; import com.logiplatform.service.*; import jakarta.validation.Valid; import org.springframework.http.ResponseEntity; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/operations") public class OperationsController { private final DispatchOperationsService dispatch; private final ProofOfDeliveryService pod; private final OperationalExceptionService exceptions; private final WarehouseWorkflowService warehouse; private final CarrierTenderService tenders; private final FleetControlService fleet; public OperationsController(DispatchOperationsService d,ProofOfDeliveryService p,OperationalExceptionService e,WarehouseWorkflowService w,CarrierTenderService c,FleetControlService f){dispatch=d;pod=p;exceptions=e;warehouse=w;tenders=c;fleet=f;}
 @PostMapping("/stops") public StopResponse addStop(@Valid @RequestBody StopRequest r){return dispatch.addStop(r);} @GetMapping("/trips/{tripId}/stops") public List<StopResponse> stops(@PathVariable UUID tripId){return dispatch.listStops(tripId);} @PostMapping("/stops/{id}/arrive") public StopResponse arrive(@PathVariable UUID id){return dispatch.arrive(id);} @PostMapping("/stops/{id}/depart") public StopResponse depart(@PathVariable UUID id){return dispatch.depart(id);} @GetMapping("/trips/{tripId}/route") public RoutePlanResponse route(@PathVariable UUID tripId){return dispatch.plan(tripId);}
 @PostMapping("/pod") public PodResponse pod(@Valid @RequestBody PodRequest r){return pod.create(r);} @GetMapping("/shipments/{shipmentId}/pod") public PodResponse getPod(@PathVariable UUID shipmentId){return pod.get(shipmentId);}
 @PostMapping("/exceptions") public ExceptionResponse exception(@Valid @RequestBody ExceptionRequest r){return exceptions.open(r);} @GetMapping("/exceptions") public List<ExceptionResponse> exceptions(@RequestParam(required=false) String status){return exceptions.list(status);} @PostMapping("/exceptions/{id}/resolve") public ExceptionResponse resolve(@PathVariable UUID id,@Valid @RequestBody ResolveExceptionRequest r){return exceptions.resolve(id,r);}
 @PostMapping("/warehouse-tasks") public WarehouseTaskResponse warehouseTask(@Valid @RequestBody WarehouseTaskRequest r){return warehouse.create(r);} @GetMapping("/warehouses/{warehouseId}/tasks") public List<WarehouseTaskResponse> warehouseTasks(@PathVariable UUID warehouseId,@RequestParam(required=false)String status){return warehouse.list(warehouseId,status);} @PostMapping("/warehouse-tasks/{id}/start") public WarehouseTaskResponse startTask(@PathVariable UUID id){return warehouse.start(id);} @PostMapping("/warehouse-tasks/{id}/complete") public WarehouseTaskResponse completeTask(@PathVariable UUID id){return warehouse.complete(id);} @PostMapping("/warehouse-tasks/{id}/cancel") public WarehouseTaskResponse cancelTask(@PathVariable UUID id){return warehouse.cancel(id);}
 @PostMapping("/tenders") public TenderResponse tender(@Valid @RequestBody TenderRequest r){return tenders.send(r);} @GetMapping("/tenders") public List<TenderResponse> tenders(){return tenders.list();} @PostMapping("/tenders/{id}/accept") public TenderResponse accept(@PathVariable UUID id,@RequestParam(required=false)String note){return tenders.accept(id,note);} @PostMapping("/tenders/{id}/reject") public TenderResponse reject(@PathVariable UUID id,@RequestParam(required=false)String note){return tenders.reject(id,note);}
 @GetMapping("/fleet/live") public List<FleetLiveResponse> fleet(){return fleet.live();}
}
