"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { ApiError, publicCommercialApi } from "@/lib/api-client";
import Icon from "@/components/Icon";

export default function QuotePage() {
  const [mode, setMode] = useState("AIRFREIGHT");
  const [form, setForm] = useState({origin:"Kigali, Rwanda",destination:"",weight:"",volume:"",packages:"",commodity:"",company:"",contactName:"",email:"",phone:"",notes:""});
  const [sent, setSent] = useState(false);
  const [quoteId, setQuoteId] = useState("");
  const [error, setError] = useState("");
  const update=(key:string,value:string)=>setForm({...form,[key]:value});
  async function submit(e:FormEvent){e.preventDefault();setError("");try{const r=await publicCommercialApi.requestQuote({origin:form.origin,destination:form.destination,serviceType:mode,commodity:form.commodity,chargeableWeightKg:Number(form.weight)||0,volumeCbm:Number(form.volume)||0,packages:Number(form.packages)||0,company:form.company,contactName:form.contactName,email:form.email,phone:form.phone,notes:form.notes});setQuoteId(r.quoteId);setSent(true)}catch(x){setError(x instanceof ApiError?x.message:"Unable to submit quote request")}}
  if(sent)return <main className="public-flow"><FlowNav/><section className="flow-success"><div className="flow-success-icon"><Icon name="shield" size={30}/></div><div className="public-eyebrow">REQUEST RECEIVED</div><h1>Your AAL quote request is in.</h1><p>Reference <strong>{quoteId}</strong>. Our commercial team can now review your route, cargo and service requirements.</p><div className="flow-success-actions"><Link className="public-main-button" href="/track">Track a shipment <Icon name="arrow" size={14}/></Link><Link className="flow-secondary" href="/">Return to AAL</Link></div></section></main>;
  return <main className="public-flow"><FlowNav/><section className="flow-layout"><div className="flow-intro"><div className="public-eyebrow">01 / QUOTE</div><h1>Tell us what needs to move.</h1><p>Request a freight quotation directly from AAL. No customer account is required to start.</p><div className="flow-benefits"><span><Icon name="shield" size={15}/> No login required</span><span><Icon name="globe" size={15}/> Air · Sea · Road</span><span><Icon name="chart" size={15}/> Commercial review</span></div></div><form className="flow-form" onSubmit={submit}><div className="flow-form-head"><span>SHIPMENT DETAILS</span><strong>Request a quote</strong></div><div className="flow-mode">{[["AIRFREIGHT","Air freight","plane"],["SEA FREIGHT","Sea freight","ship"],["ROAD FREIGHT","Road freight","truck"]].map(([v,l,i])=><button type="button" className={mode===v?"selected":""} onClick={()=>setMode(v)} key={v}><Icon name={i as any} size={17}/>{l}</button>)}</div><div className="flow-grid"><Field label="Origin" value={form.origin} onChange={v=>update("origin",v)}/><Field label="Destination" value={form.destination} onChange={v=>update("destination",v)}/><Field label="Gross / chargeable weight (kg)" value={form.weight} onChange={v=>update("weight",v)} type="number"/><Field label="Volume (CBM)" value={form.volume} onChange={v=>update("volume",v)} type="number"/><Field label="Packages" value={form.packages} onChange={v=>update("packages",v)} type="number"/><Field label="Commodity" value={form.commodity} onChange={v=>update("commodity",v)}/><Field label="Company" value={form.company} onChange={v=>update("company",v)}/><Field label="Contact name" value={form.contactName} onChange={v=>update("contactName",v)}/><Field label="Email" value={form.email} onChange={v=>update("email",v)} type="email"/><Field label="Phone" value={form.phone} onChange={v=>update("phone",v)}/></div><label className="flow-textarea"><span>Additional requirements</span><textarea value={form.notes} onChange={e=>update("notes",e.target.value)} rows={3}/></label>{error&&<div className="alert alert-error">{error}</div>}<button className="public-main-button flow-submit">Request AAL quote <Icon name="arrow" size={14}/></button><small className="flow-privacy">Your request is submitted securely to AAL.</small></form></section></main>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="flow-field"><span>{label}</span><input required value={value} type={type} onChange={e=>onChange(e.target.value)}/></label>}
function FlowNav(){return <nav className="public-nav flow-nav"><Link href="/" className="public-brand"><span className="public-brand-mark"><Icon name="plane" size={20}/></span><span><strong>AAL</strong><small>AFRICA LOGISTIC AVIATION</small></span></Link><div className="flow-nav-links"><Link href="/">Home</Link><Link href="/track">Track</Link><Link href="/login">Staff sign in</Link></div></nav>}
