CREATE ROLE aal_backup LOGIN REPLICATION BYPASSRLS PASSWORD :'backup_password';

GRANT CONNECT ON DATABASE aal TO aal_backup;
GRANT USAGE ON SCHEMA public TO aal_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO aal_backup;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO aal_backup;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO aal_backup;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO aal_backup;
